spring:
  datasource:
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:file:@project.basedir@/db/cityinfo
    username: user
    password: password
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  jackson:
    default-property-inclusion: non_null
  data:
    rest:
      base-path: /api
      return-body-on-create: true
bot.token: 1291049500:AAGL0VfHiOgyoVmwbOIEkAOqvepHHMvGb-A
bot.username: TravelCityInfo_bot
